[project]
name = "backend-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.16.2",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E","W", "F", "I", "C90", "UP"]
ignore = []

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
